### ISSUE TITLE
using previous/next spotify ALWAYS skips 2 songs instead of 1

### ISSUE THREAD

**Issue by liquidfrogs** [zopieux/spotify-hotkeys#14] opened 2023-05-16 20:02 UTC
title.

**Comment by zopieux** [comment] 2023-05-18 14:57
Hi, I just tried on my browser and could not reproduce the issue :(

If you don't mind, for me to debug your issue, I would appreciate if you could share a screencast of the problem.

1. [install a screencasting extension](https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en)
1. launch some playlist on Spotify Web
1. make sure to open the Spotify queue view ("stack" button on the bottom bar)
1. start the screencast recording
1. use the key bindings to demo the double-skip issue in both directions
1. stop recording and upload the file to this issue (drag & drop), or if it's too large for GitHub, try https://streamable.com instead

Thanks!

**Comment by frypf** [comment] 2023-08-11 16:26
I actually noticed this once a while back, but realised I had another Spotify tab open in another window, so the command was being sent to both tabs. It seems reproducible - and extensible, ie. having 3 open Spotify tabs will skip 3 tracks etc.

**Comment by zopieux** [comment] 2023-08-20 15:46
Thanks @frypf, your PR looks good to me and solves this, so let's get it merged :-) Sent a review.

**Comment by zopieux** [comment] 2023-08-26 22:27
Fixed by #15.

**Closed by zopieux** 2023-08-26 22:27 UTC
Labels: bug
